### ISSUE TITLE
Insecure Highcharts.js

### ISSUE THREAD

**Issue by kuuji** [cloudwalkio/fleet-browser#11]
Hello ! 

I'm trying to include your fleet browser into my coreos cluster which is behind an haproxy (configured via confd + etcd).

My haproxy only work in https. And fleet browser is loading highchart js dependency via the http url which is not allowed. Only the dashboard is affected.

Regards,

Kuuji.
![capture d ecran de 2015-10-06 11-37-52](https://cloud.githubusercontent.com/assets/2299504/10305143/d26d24de-6c1e-11e5-968f-1916e7cfe7d9.png)
![capture d ecran de 2015-10-06 11-38-02](https://cloud.githubusercontent.com/assets/2299504/10305150/d933ce8a-6c1e-11e5-9208-4c35a764de9e.png)

**Comment by allanino** [comment]
It should be fixed by #12.
