### ISSUE TITLE
Fleet Metadata not displayed in machines tab

### ISSUE THREAD

**Issue by sxchapma** [cloudwalkio/fleet-browser#15]
Would it be possible to display any fleet metadata in the machines tab, it is very useful to see what metadata there is.

**Comment by allanino** [comment]
hi @sxchapma!

Sorry for the late response, but I will study how to get this metadata. It should not be too difficult.

**Comment by sxchapma** [comment]
Allan,

thanks it will really help and will make it more like the command line tool
