### ISSUE TITLE
New version 1.1.1 metadata has miscellaneous "u" character in display on Chrome on Mac

### ISSUE THREAD

**Issue by sxchapma** [cloudwalkio/fleet-browser#16]
I am using the newest version with the metadata and when it displays the metadata has a "u" character before every name and value of the metadata pair.

I am enclosing a pic of the issue

Thanks
Scott
![screen shot 2016-08-26 at 10 27 13 am](https://cloud.githubusercontent.com/assets/20248477/18014539/35db76fc-6b78-11e6-9c51-4b3982acc8bd.png)

**Comment by allanino** [comment]
Oh, I see. That's easy to fix.

**Comment by allanino** [comment]
Hi @sxchapma, can you please test it with Docker image `quay.io/cloudwalk/fleet-browser:master`?

I'll release this as `v1.1.2` after you test it.

**Comment by sxchapma** [comment]
Sorry for the delay, it looks good now no extra "u"

thanks much

Scott
