### ISSUE TITLE
Creating new units with multi-line commands can fail

### ISSUE THREAD

**Issue by allanino** [cloudwalkio/fleet-browser#4]
The current function used to serialize unit files to JSON is a bit limited: https://github.com/cloudwalkio/fleet-browser/blob/master/app.py#L28

It doesn't work very well with multi-line commands. Fleet uses a go package to handle that: https://github.com/coreos/fleet/blob/077109f4dd5c99ed034cbed8307db9d516db9fc9/Godeps/_workspace/src/github.com/coreos/go-systemd/unit/deserialize.go

We should create something similar for Python.

**Comment by allanino** [comment]
We haven't found any case of units not working properly after the commit above.

As this seems to handle the majority of cases and is much simpler than the proposed approach, I'm closing this for now.

If anyone found problems related to this, feel free to reopen this issue.

**Comment by maiconio** [comment]
Great!
