### ISSUE TITLE
Global units have wrong status

### ISSUE THREAD

**Issue by madeddie** [cloudwalkio/fleet-browser#6]
[on the Units tab]
Any units configured with X-Fleet Global=true show as State "inactive" and Target "-".
fleetctl shows them as State "-" and Target "global" which makes a bit more sense.

I think if the Target is "global" and the State is "-" and Dstate is "launched", the row should be green.
If the Target is "global", the State is "-" (which it always is) and Dstate is "inactive" (submitted) or "loaded", it could and maybe should be yellow as it now always is.

**Comment by madeddie** [comment]
Also, thanks for making fleet-browser :) I'll try to make a PR out if this.

**Comment by allanino** [comment]
Thanks for reporting this issue!
We don't use global units for now, so I couldn't have caught this.
I'll wait for your PR ;)
